### ISSUE TITLE
La distancia ente producto y usuario no es correcta

### ISSUE THREAD

**Issue by torvic98** [unizar-30226-2019-07/Break#7]
Por si no habías tenido tiempo de encontrar la causa del *bug*, @end222, el problema de las distancias erróneas es este:
https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L199-L201

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L277-L278

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L325-L327

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L403-L404

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L449

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L526

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L547

https://github.com/unizar-30226-2019-07/Break/blob/5b8e3b3069c99572a4cbf9c8005767aba7e18f28/web/app/__init__.py#L569-L570

Intentaré solventarlo en mi próximo *commit*.

**Comment by end222** [comment]
He corregido ahora el error. El principal problema estaba además en que las distancias se mostraban multiplicadas por 1000, ya que la API las envía en metros y las estábamos tratando como KM
